@startuml Диаграмма активности - Загрузка файла
!theme plain

start

:Пользователь выбирает файл(ы);

:Создать объект FormData;

if (Один файл?) then (да)
  :Добавить файл в FormData;
else (нет)
  :Добавить несколько файлов в FormData;
endif

:Отправить POST запрос к API;

:Сервер получает запрос;

if (Режим хранилища?) then (Локальное)
  :Сохранить в локальное хранилище;
  :Записать файл на диск;
  :Сохранить метаданные JSON;
else (AWS S3)
  :Проверить AWS credentials;
  if (Валидные credentials?) then (да)
    :Загрузить в S3 bucket;
  else (нет)
    :Вернуть ошибку;
    stop
  endif
endif

if (Загрузка успешна?) then (да)
  :Вернуть ответ об успехе;
  :Обновить интерфейс;
  :Показать сообщение об успехе;
  :Обновить список файлов;
else (нет)
  :Вернуть ответ об ошибке;
  :Показать сообщение об ошибке;
endif

stop

@enduml
